var charData = {
    "Sirius (Midsummer Seirios)": "tianlangxing_3",
    
    "Bismarck (Majesty of the Ironblood)": "bisimai_2",
    "Ark Royal (Banquet Guardian)": "huangjiafangzhou_3",
    
    "Taihou (Forbidden Feast)": "dafeng_2",
    "Atago (Midsummer March)": "aidang_2",
    "Eldridge (New Year's Handholding)": "aierdeliqi_4",
    "Emile Bertin (Côte d'Azur)": "aimierbeierding_2",
    "Centaur (Undine of the Beach)": "banrenma_2",
    "Belfast (Iridescent Rose)": "beierfasite_2",
    "Javelin": "biaoqiang",
    "Javelin (Beach Picnic!)": "biaoqiang_3",
    "Fubuki (Music Pixy)": "chuixue_3",
    "Deutschland (Service Time?!)": "deyizhi_3",
    "Unicorn (Amusement Park Date)": "dujiaoshou_4",
    "Dunkerque (Summer Sucré)": "dunkeerke_2",
    "Honolulu (Summer Accident?!)": "huonululu_3",
    "Cleveland (Gentry Knight)": "kelifulan_3",
    "Laffey": "lafei",
    "Laffey (New Year Rabbit)": "lafei_4",
    "Ayanami": "lingbo",
    "Akashi": "mingshi",
    "Graf Zeppelin (Beachside Urd)": "qibolin_2",
    "St. Louis (Splendor of Spring)": "shengluyisi_2",
    "St. Louis (Tipsy Snow)": "shengluyisi_3",
    "Tai Yuan (Clamorous Tortoise)": "taiyuan_2",
    "Tirpitz (Snow-melting Summer)": "tierbici_2",
    "Yukikaze": "xuefeng",
    "Ibuki (Wish of a Snow Goddess)": "yichui_2",
    "Z23": "z23",
    "Z46 (First Summer)": "z46_2",
};
